import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export interface ColorTheme {
  id: string
  name: string
  category: string
  colors: {
    primary: string
    secondary: string
    accent: string
    background: string
    surface: string
    textPrimary: string
    textSecondary: string
    textOnPrimary: string
    border: string
    success: string
    warning: string
    error: string
  }
}
export interface Gradient {
  id: string
  name: string
  type: 'linear' | 'radial' | 'conic'
  stops: { color: string; position: number }[]
  angle?: number
}
interface ColorState {
  activeTheme: ColorTheme
  themes: ColorTheme[]
  gradients: Gradient[]
  recentColors: string[]
  savedColors: string[]
  setActiveTheme: (theme: ColorTheme) => void
  updateThemeColor: (key: keyof ColorTheme['colors'], value: string) => void
  addRecentColor: (color: string) => void
  addSavedColor: (color: string) => void
  removeSavedColor: (color: string) => void
}
const defaultThemes: ColorTheme[] = [
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'Professional',
    colors: {
      primary: '#1E3A5F',
      secondary: '#4A6FA5',
      accent: '#7FB069',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      textPrimary: '#1E293B',
      textSecondary: '#64748B',
      textOnPrimary: '#FFFFFF',
      border: '#E2E8F0',
      success: '#22C55E',
      warning: '#EAB308',
      error: '#EF4444',
    },
  },
  {
    id: 'legal-gray',
    name: 'Legal Gray',
    category: 'Professional',
    colors: {
      primary: '#374151',
      secondary: '#6B7280',
      accent: '#D97706',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      textPrimary: '#1F2937',
      textSecondary: '#6B7280',
      textOnPrimary: '#FFFFFF',
      border: '#E5E7EB',
      success: '#059669',
      warning: '#D97706',
      error: '#DC2626',
    },
  },
  {
    id: 'finance-trust',
    name: 'Finance Trust',
    category: 'Professional',
    colors: {
      primary: '#1E40AF',
      secondary: '#94A3B8',
      accent: '#059669',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      textOnPrimary: '#FFFFFF',
      border: '#CBD5E1',
      success: '#059669',
      warning: '#F59E0B',
      error: '#DC2626',
    },
  },
  {
    id: 'minimal-paper',
    name: 'Paper',
    category: 'Minimalist',
    colors: {
      primary: '#1A1A1A',
      secondary: '#666666',
      accent: '#E85D04',
      background: '#FAFAF9',
      surface: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#737373',
      textOnPrimary: '#FFFFFF',
      border: '#E5E5E5',
      success: '#16A34A',
      warning: '#CA8A04',
      error: '#DC2626',
    },
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian',
    category: 'Minimalist',
    colors: {
      primary: '#2D3436',
      secondary: '#B2BEC3',
      accent: '#00B894',
      background: '#FDFEFE',
      surface: '#FFFFFF',
      textPrimary: '#2D3436',
      textSecondary: '#636E72',
      textOnPrimary: '#FFFFFF',
      border: '#DFE6E9',
      success: '#00B894',
      warning: '#FDCB6E',
      error: '#E17055',
    },
  },
  {
    id: 'japanese',
    name: 'Japanese',
    category: 'Minimalist',
    colors: {
      primary: '#2C3E50',
      secondary: '#95A5A6',
      accent: '#C0392B',
      background: '#FAF8F5',
      surface: '#FFFFFF',
      textPrimary: '#2C3E50',
      textSecondary: '#7F8C8D',
      textOnPrimary: '#FFFFFF',
      border: '#ECF0F1',
      success: '#27AE60',
      warning: '#F39C12',
      error: '#C0392B',
    },
  },
  {
    id: 'swiss',
    name: 'Swiss',
    category: 'Minimalist',
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#FF0000',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      textPrimary: '#000000',
      textSecondary: '#666666',
      textOnPrimary: '#FFFFFF',
      border: '#E0E0E0',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#F44336',
    },
  },
  {
    id: 'startup-energy',
    name: 'Startup Energy',
    category: 'Bold',
    colors: {
      primary: '#6366F1',
      secondary: '#EC4899',
      accent: '#10B981',
      background: '#0F172A',
      surface: '#1E293B',
      textPrimary: '#F8FAFC',
      textSecondary: '#94A3B8',
      textOnPrimary: '#FFFFFF',
      border: '#334155',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    category: 'Bold',
    colors: {
      primary: '#8B5CF6',
      secondary: '#06B6D4',
      accent: '#F97316',
      background: '#18181B',
      surface: '#27272A',
      textPrimary: '#FAFAFA',
      textSecondary: '#A1A1AA',
      textOnPrimary: '#000000',
      border: '#3F3F46',
      success: '#22C55E',
      warning: '#FBBF24',
      error: '#F43F5E',
    },
  },
  {
    id: 'tech-forward',
    name: 'Tech Forward',
    category: 'Bold',
    colors: {
      primary: '#3B82F6',
      secondary: '#1E293B',
      accent: '#22D3EE',
      background: '#0F172A',
      surface: '#1E293B',
      textPrimary: '#F1F5F9',
      textSecondary: '#94A3B8',
      textOnPrimary: '#FFFFFF',
      border: '#334155',
      success: '#34D399',
      warning: '#FBBF24',
      error: '#F87171',
    },
  },
  {
    id: 'fashion-edge',
    name: 'Fashion Edge',
    category: 'Bold',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
      accent: '#EC4899',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      textPrimary: '#000000',
      textSecondary: '#525252',
      textOnPrimary: '#FFFFFF',
      border: '#E5E5E5',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
    },
  },
  {
    id: 'artisan',
    name: 'Artisan',
    category: 'Warm',
    colors: {
      primary: '#9A3412',
      secondary: '#78350F',
      accent: '#166534',
      background: '#FFFBEB',
      surface: '#FEF3C7',
      textPrimary: '#451A03',
      textSecondary: '#78350F',
      textOnPrimary: '#FFFFFF',
      border: '#FDE68A',
      success: '#166534',
      warning: '#B45309',
      error: '#B91C1C',
    },
  },
  {
    id: 'organic',
    name: 'Organic',
    category: 'Warm',
    colors: {
      primary: '#4D7C0F',
      secondary: '#A16207',
      accent: '#92400E',
      background: '#FEFCE8',
      surface: '#F7FEE7',
      textPrimary: '#365314',
      textSecondary: '#4D7C0F',
      textOnPrimary: '#FFFFFF',
      border: '#D9F99D',
      success: '#16A34A',
      warning: '#CA8A04',
      error: '#DC2626',
    },
  },
  {
    id: 'bakery',
    name: 'Bakery',
    category: 'Warm',
    colors: {
      primary: '#881337',
      secondary: '#BE123C',
      accent: '#B45309',
      background: '#FFF1F2',
      surface: '#FFE4E6',
      textPrimary: '#4C0519',
      textSecondary: '#881337',
      textOnPrimary: '#FFFFFF',
      border: '#FECDD3',
      success: '#15803D',
      warning: '#D97706',
      error: '#BE123C',
    },
  },
  {
    id: 'wellness',
    name: 'Wellness',
    category: 'Warm',
    colors: {
      primary: '#059669',
      secondary: '#7C3AED',
      accent: '#0891B2',
      background: '#F0FDF4',
      surface: '#DCFCE7',
      textPrimary: '#14532D',
      textSecondary: '#166534',
      textOnPrimary: '#FFFFFF',
      border: '#BBF7D0',
      success: '#16A34A',
      warning: '#CA8A04',
      error: '#DC2626',
    },
  },
  {
    id: 'developer-dark',
    name: 'Developer Dark',
    category: 'Dark',
    colors: {
      primary: '#22D3EE',
      secondary: '#A78BFA',
      accent: '#34D399',
      background: '#000000',
      surface: '#171717',
      textPrimary: '#FAFAFA',
      textSecondary: '#A3A3A3',
      textOnPrimary: '#000000',
      border: '#262626',
      success: '#34D399',
      warning: '#FBBF24',
      error: '#F87171',
    },
  },
  {
    id: 'luxury-dark',
    name: 'Luxury Dark',
    category: 'Dark',
    colors: {
      primary: '#D4AF37',
      secondary: '#C9A962',
      accent: '#B8860B',
      background: '#0A0A0A',
      surface: '#171717',
      textPrimary: '#FAFAF9',
      textSecondary: '#A8A29E',
      textOnPrimary: '#000000',
      border: '#292524',
      success: '#22C55E',
      warning: '#D4AF37',
      error: '#EF4444',
    },
  },
  {
    id: 'cinema',
    name: 'Cinema',
    category: 'Dark',
    colors: {
      primary: '#DC2626',
      secondary: '#1F2937',
      accent: '#F59E0B',
      background: '#111827',
      surface: '#1F2937',
      textPrimary: '#F9FAFB',
      textSecondary: '#9CA3AF',
      textOnPrimary: '#FFFFFF',
      border: '#374151',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#DC2626',
    },
  },
  {
    id: 'night-mode',
    name: 'Night Mode',
    category: 'Dark',
    colors: {
      primary: '#60A5FA',
      secondary: '#1E3A5F',
      accent: '#A78BFA',
      background: '#0F172A',
      surface: '#1E293B',
      textPrimary: '#E2E8F0',
      textSecondary: '#94A3B8',
      textOnPrimary: '#0F172A',
      border: '#334155',
      success: '#4ADE80',
      warning: '#FACC15',
      error: '#F87171',
    },
  },
]
const additionalThemes: ColorTheme[] = [
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    category: 'Nature',
    colors: {
      primary: '#0077B6',
      secondary: '#00B4D8',
      accent: '#90E0EF',
      background: '#F8FDFF',
      surface: '#FFFFFF',
      textPrimary: '#03045E',
      textSecondary: '#023E8A',
      textOnPrimary: '#FFFFFF',
      border: '#CAF0F8',
      success: '#2DC653',
      warning: '#FFB703',
      error: '#E63946',
    },
  },
  {
    id: 'forest-calm',
    name: 'Forest Calm',
    category: 'Nature',
    colors: {
      primary: '#2D6A4F',
      secondary: '#40916C',
      accent: '#95D5B2',
      background: '#F7FDF9',
      surface: '#FFFFFF',
      textPrimary: '#1B4332',
      textSecondary: '#52796F',
      textOnPrimary: '#FFFFFF',
      border: '#D8F3DC',
      success: '#2D6A4F',
      warning: '#FB8500',
      error: '#D00000',
    },
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'Nature',
    colors: {
      primary: '#E85D04',
      secondary: '#F48C06',
      accent: '#FAA307',
      background: '#FFFAF5',
      surface: '#FFFFFF',
      textPrimary: '#370617',
      textSecondary: '#6A040F',
      textOnPrimary: '#FFFFFF',
      border: '#FFE5D0',
      success: '#38B000',
      warning: '#F48C06',
      error: '#D00000',
    },
  },
  {
    id: 'lavender-fields',
    name: 'Lavender Fields',
    category: 'Nature',
    colors: {
      primary: '#7B2CBF',
      secondary: '#9D4EDD',
      accent: '#C77DFF',
      background: '#FBF8FF',
      surface: '#FFFFFF',
      textPrimary: '#3C096C',
      textSecondary: '#5A189A',
      textOnPrimary: '#FFFFFF',
      border: '#E7D8F5',
      success: '#38B000',
      warning: '#FFAA00',
      error: '#E63946',
    },
  },
  {
    id: 'cyber-punk',
    name: 'Cyber Punk',
    category: 'Tech',
    colors: {
      primary: '#FF00FF',
      secondary: '#00FFFF',
      accent: '#FFFF00',
      background: '#0D0221',
      surface: '#1A0A2E',
      textPrimary: '#FFFFFF',
      textSecondary: '#B8B8D1',
      textOnPrimary: '#000000',
      border: '#3D2066',
      success: '#00FF00',
      warning: '#FFD600',
      error: '#FF0054',
    },
  },
  {
    id: 'neo-tokyo',
    name: 'Neo Tokyo',
    category: 'Tech',
    colors: {
      primary: '#E60073',
      secondary: '#00D4FF',
      accent: '#FFE600',
      background: '#0A0A0F',
      surface: '#141420',
      textPrimary: '#FFFFFF',
      textSecondary: '#9999AA',
      textOnPrimary: '#000000',
      border: '#2A2A3A',
      success: '#00FF88',
      warning: '#FFE600',
      error: '#FF0055',
    },
  },
  {
    id: 'matrix-green',
    name: 'Matrix',
    category: 'Tech',
    colors: {
      primary: '#00FF41',
      secondary: '#008F11',
      accent: '#00FF41',
      background: '#0D0208',
      surface: '#1A0A14',
      textPrimary: '#00FF41',
      textSecondary: '#008F11',
      textOnPrimary: '#000000',
      border: '#003B00',
      success: '#00FF41',
      warning: '#FFD600',
      error: '#FF073A',
    },
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    category: 'Luxury',
    colors: {
      primary: '#B8860B',
      secondary: '#DAA520',
      accent: '#FFD700',
      background: '#FFFEF5',
      surface: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#4A4A4A',
      textOnPrimary: '#000000',
      border: '#F0E6D3',
      success: '#228B22',
      warning: '#DAA520',
      error: '#8B0000',
    },
  },
  {
    id: 'rose-gold-luxury',
    name: 'Rose Gold',
    category: 'Luxury',
    colors: {
      primary: '#B76E79',
      secondary: '#E8B4B8',
      accent: '#F8D3D6',
      background: '#FFF9F9',
      surface: '#FFFFFF',
      textPrimary: '#2D2D2D',
      textSecondary: '#6B6B6B',
      textOnPrimary: '#FFFFFF',
      border: '#F5E6E8',
      success: '#4A9B7F',
      warning: '#D4A574',
      error: '#A85858',
    },
  },
  {
    id: 'platinum-elite',
    name: 'Platinum Elite',
    category: 'Luxury',
    colors: {
      primary: '#4A4A4A',
      secondary: '#7A7A7A',
      accent: '#C0C0C0',
      background: '#FAFAFA',
      surface: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#5A5A5A',
      textOnPrimary: '#FFFFFF',
      border: '#E5E5E5',
      success: '#3D8B40',
      warning: '#C9A227',
      error: '#B33A3A',
    },
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    category: 'Pastel',
    colors: {
      primary: '#FFB3D9',
      secondary: '#B3E0FF',
      accent: '#FFFACD',
      background: '#FFFBFE',
      surface: '#FFFFFF',
      textPrimary: '#4A4A4A',
      textSecondary: '#7A7A7A',
      textOnPrimary: '#4A4A4A',
      border: '#FFE4F0',
      success: '#90EE90',
      warning: '#FFE4B5',
      error: '#FFB6C1',
    },
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    category: 'Pastel',
    colors: {
      primary: '#98D8C8',
      secondary: '#7EC8E3',
      accent: '#B5EAD7',
      background: '#F5FFFA',
      surface: '#FFFFFF',
      textPrimary: '#2D4A3E',
      textSecondary: '#5A7A6E',
      textOnPrimary: '#1A1A1A',
      border: '#D0F0E0',
      success: '#7BC47F',
      warning: '#FFD966',
      error: '#E88888',
    },
  },
  {
    id: 'peach-dream',
    name: 'Peach Dream',
    category: 'Pastel',
    colors: {
      primary: '#FFCBA4',
      secondary: '#FFE5B4',
      accent: '#FFDAB9',
      background: '#FFFAF0',
      surface: '#FFFFFF',
      textPrimary: '#4A3728',
      textSecondary: '#7A6758',
      textOnPrimary: '#3A2A1A',
      border: '#FFE8D6',
      success: '#9ACD32',
      warning: '#FFD700',
      error: '#E57373',
    },
  },
]
const defaultGradients: Gradient[] = [
  { id: 'g1', name: 'Sunset', type: 'linear', angle: 135, stops: [{ color: '#F97316', position: 0 }, { color: '#EC4899', position: 100 }] },
  { id: 'g2', name: 'Ocean', type: 'linear', angle: 180, stops: [{ color: '#06B6D4', position: 0 }, { color: '#3B82F6', position: 100 }] },
  { id: 'g3', name: 'Forest', type: 'linear', angle: 135, stops: [{ color: '#22C55E', position: 0 }, { color: '#14B8A6', position: 100 }] },
  { id: 'g4', name: 'Midnight', type: 'linear', angle: 180, stops: [{ color: '#1E293B', position: 0 }, { color: '#0F172A', position: 100 }] },
  { id: 'g5', name: 'Aurora', type: 'linear', angle: 135, stops: [{ color: '#8B5CF6', position: 0 }, { color: '#06B6D4', position: 50 }, { color: '#10B981', position: 100 }] },
  { id: 'g6', name: 'Fire', type: 'linear', angle: 180, stops: [{ color: '#F97316', position: 0 }, { color: '#EF4444', position: 100 }] },
  { id: 'g7', name: 'Silver', type: 'linear', angle: 135, stops: [{ color: '#94A3B8', position: 0 }, { color: '#CBD5E1', position: 100 }] },
  { id: 'g8', name: 'Gold', type: 'linear', angle: 135, stops: [{ color: '#D4AF37', position: 0 }, { color: '#B8860B', position: 100 }] },
  { id: 'g9', name: 'Neon', type: 'linear', angle: 45, stops: [{ color: '#FF00FF', position: 0 }, { color: '#00FFFF', position: 100 }] },
  { id: 'g10', name: 'Emerald', type: 'linear', angle: 135, stops: [{ color: '#047857', position: 0 }, { color: '#10B981', position: 100 }] },
  { id: 'g11', name: 'Rose', type: 'linear', angle: 135, stops: [{ color: '#BE123C', position: 0 }, { color: '#FB7185', position: 100 }] },
  { id: 'g12', name: 'Indigo', type: 'linear', angle: 180, stops: [{ color: '#4338CA', position: 0 }, { color: '#818CF8', position: 100 }] },
]
const allThemes = [...defaultThemes, ...additionalThemes]
export const useColorStore = create<ColorState>()(
  persist(
    (set) => ({
      activeTheme: allThemes[0],
      themes: allThemes,
      gradients: defaultGradients,
      recentColors: [],
      savedColors: [],
      setActiveTheme: (activeTheme) => set({ activeTheme }),
      updateThemeColor: (key, value) => set((state) => {
        const updatedActiveTheme = { ...state.activeTheme, colors: { ...state.activeTheme.colors, [key]: value } }
        const updatedThemes = state.themes.map(t => t.id === state.activeTheme.id ? updatedActiveTheme : t)
        return {
          activeTheme: updatedActiveTheme,
          themes: updatedThemes
        }
      }),
      addRecentColor: (color) => set((state) => {
        const filtered = state.recentColors.filter((c) => c !== color)
        return { recentColors: [color, ...filtered].slice(0, 12) }
      }),
      addSavedColor: (color) => set((state) => ({
        savedColors: state.savedColors.includes(color) ? state.savedColors : [...state.savedColors, color],
      })),
      removeSavedColor: (color) => set((state) => ({
        savedColors: state.savedColors.filter((c) => c !== color),
      })),
    }),
    { name: 'designforge-colors' }
  )
)